default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 127.0.0.1
  username: <%= ENV.fetch("DATABASE_USERNAME", "booking_platform") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "booking_platform_pass") %>
  port: 5432

development:
  <<: *default
  database: booking_platform_development

test:
  <<: *default
  database: booking_platform_test

staging:
  <<: *default
  database: booking_platform_staging
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

production:
  <<: *default
  database: booking_platform_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  prepared_statements: true